# Generated by Django 3.1.4 on 2021-01-29 09:23

import collections
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mage2gen', '0004_module_download_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='config',
            field=jsonfield.fields.JSONField(default={}, load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
    ]
