# Generated by Django 6.1.1 on 2026-09-28 11:06

import collections
import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mage2gen', '0005_auto_20210129_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='config',
            field=jsonfield.fields.JSONField(default=dict, load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
    ]
